spring:  
  jpa:  
    hibernate:  
      ddl-auto: update  
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/refp?useTimezone=true&serverTimezone=UTC
    username: root
    password: refp
    
awsinfo:
  accesskey: AKIAV2J2NVHCS7FEPO3B
  secretKey: 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
  bucketName: refp
  region: sa-east-1